# CPGvulnHunter 统一配置文件
project_name: "CPGvulnHunter"
version: "1.0.0"
debug_mode: false

# LLM配置
llm:
  base_url: "http://192.168.5.253:3000/api/"
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjN2ZjYWI0LWNkYTctNDQ5MC04Y2VkLThmZDNjNDQ0ODM4MyJ9.EF4VyeqVO0rfgN5mpFWYYZEaarcOXSQ1vjw-UYVCfkI"
  model: "qwen2.5:14b"
  temperature: 0.7
  max_tokens: 2048
  timeout: 30

# Joern配置
joern:
  installation_path: "/home/nstl/data/vuln_hunter/heouJoern/joern/joern-cli/target/universal/stage/joern"
  timeout: 300
  memory_limit: "8G"
  cpg_var: "cpg"
  workspace_path: "workspace"
  enable_cache: true
  cache_dir: "cache"

# Engine核心配置
engine:
  max_call_depth: 20
  timeout_per_pass: 300
  parallel_execution: false
  max_functions: 1000
  output_dir: "output"
  save_intermediate_results: true
  report_format: "json"
  enabled_passes: ["init"]
  pass_config:
    cwe78:
      confidence_threshold: 0.6
      max_sources: 50
      max_sinks: 50
  pass_registry:
      init: "CPGvulnHunter.passes.initPass.InitPass"
      cwe78: "CPGvulnHunter.passes.cwe78.CWE78"
  enabled_passes: ["init", "cwe78"]
# 漏洞检测配置
vulnerability_detection:
  timeout: 300
  confidence_threshold: 0.6
  max_paths: 100
  enable_path_optimization: true
  cwe_types: ["CWE-78"]

# 日志配置
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  file: "logs/cpgvulnhunter.log"
  max_file_size: "10MB"
  backup_count: 5